Test next transform

diff --git a/mrbtp/transform b/mrbtp/transform
--- a/mrbtp/transform
+++ b/mrbtp/transform
@@ -15,27 +15,71 @@
 #################
 # CONFIGURATION #
 #################
-BACKUPDIR="transform-backups"
-# Set this to the largest number of slashes we
-# might find in the input source references
-MAXSLASHES=1
 
 #############
 # FUNCTIONS #
 #############
 
-# If $OUTPUT exists, save a copy in $BACKUPDIR
-backup_output_file () {
-    if [ ! -d ${BACKUPDIR} ]; then
-        mkdir -p ${BACKUPDIR}
-    fi
-    
-    if [ -f $OUTPUT ]; then
-	cp -p ${OUTPUT} `date "+${BACKUPDIR}/${OUTPUT}.%Y%m%d-%H%M%S"`
-    fi
+##########################################################
+# Print out help message for using the program and exit. #
+##########################################################
+
+helpmsg () {
+    echo "${PROGNAME} [-h|--help] [-o|--output] <outputfile> <inputfile>"
+    echo ""
+    echo "Transform a CSV file for input to AHCIP"
+    echo "-h or --help displays this help message"
+    echo "target-directory should be a relative or absolute path pointing to a directory to be cleaned"
 }
+
+##########################################################
+# Parse the arguments on the command line                #
+##########################################################
+
+parse_commandline () {
+
+    outfile=''
+    while [ $# -gt 1 ]
+    do
+	case $1 in
+	    -h | --help )
+		helpmsg
+		exit 0
+		;;
+
+	    -o | --output )
+		if [ "X$2" != "X" ]; then
+		    outfile=$2
+		    shift
+		else
+		    helpmsg
+		    exit 1
+		    ;;
+		fi
+	esac
+
+	shift
+    done
+
+    lastparam=$1
+
+    if [ X${lastparam} = X ]; then helpmsg; exit 1; fi
+
+    if [[ ${lastparam} =~ ^(-h|--help)$ ]]; then helpmsg; exit 0; fi
+
+    export SRCFILE=${lastparam}
     
-# Apply an ex file to $OUTPUT
+    if [ X${outfile} = X ]
+    then
+	outfile="`basename ${SRCFILE}`_ahcip.csv"
+    fi
+    export OUTFILE="${outfile}"
+
+}
+
+###############################
+# Apply an ex file to $OUTPUT #
+###############################
 apply_ex_file () {
     exfile=$1
 
@@ -46,11 +90,10 @@ apply_ex_file () {
 
     echo "Applying ${exfile}"
 
-    ex -S ${exfile} ${OUTPUT}
+    ex -S ${exfile} ${OUTFILE}
     
     echo "Finished applying ${exfile}"
 }
-
 
 ############################
 # MAIN PROGRAM BEGINS HERE #
@@ -58,25 +101,25 @@ apply_ex_file () {
 
 export PROGNAME=`basename $0`
 
-SRCFILE=$1
-OUTPUT="`basename $1`_ahcip.csv"
+parse_commandline $*
+
+if [ ! -r ${SRCFILE} ]
+then
+  echo "Unable to read ${SRCFILE}"
+  exit 1
+fi  
 
 # Running ex is a destructive process
-backup_output_file
-cp -p ${SRCFILE} ${OUTPUT}
+cp -p ${SRCFILE} ${OUTFILE}
 
-# A slash source reference like I.16.122-124/127-128
-# gets split into two lines. There can be multiple
-# slashes to a source reference, so we have to run
-# multiple times.
-counter=0
-while [ $counter -lt $MAXSLASHES ]
-do
-    apply_ex_file split-slash-refs.ex
-    counter=$((counter+1))
-done
+# Split slash source references like I.16.122-124/127-128
+# If there are more than six slashes in an input line, 
+# edit the script
+apply_ex_file split-slash-refs.ex
 
-
+# Split comma references in commentary clauses
+# like 
+apply_ex_file split-comma-refs.ex
 
 ### These transforms should be done last!
 
